const labels = {
    'en': {
        'all': 'Select All',
        'none': 'Deselect All',
        'ready': 'Ready',
        'done': 'Done',
        'cancel': 'Cancel',
        'selected': 'Selected',
        'gap': 'Interval',
        'sec': 'sec',
        'voice': '📢 Voice',
        'bg': '🎵 Background',
        'shuffle_and_play': 'Shuffle & Start',
        'play_or_pause': 'Play / Pause',
        'resume': 'Resume',
        'pause': 'Pause',
        'steps': 'In Progress',
        'status_info': 'Tap ⚙️ to select actions to add to your routine.',
        'alert_min_one': 'Please select at least one action!',
        'status_finished': 'Workout completed.',
        'finished': 'Finished!',
        'loading_sounds' : 'On loading voice data...'
    },
    'ko': {
        'all' : '모두 선택',
        'none' : '모두 제외',
        'ready' : '준비',
        'done': '완료',
        'cancel': '취소',
        'selected' : '선택됨',
        'gap': '간격',
        'sec': '초',
        'voice': '📢 음성',
        'bg': '🎵 배경',
        'shuffle_and_play' : '루틴 셔플 & 시작',
        'play_or_pause' : '재생 / 일시중지',
        'resume' : '루틴 재개',
        'pause' : '일시중지',
        'steps' : '진행 중',
        'status_info' : '⚙️를 눌러서, 루틴에 추가할 동작을 선택할 수 있습니다.',
        'alert_min_one': '최소 하나 이상의 동작을 선택해주세요!',
        'status_finished' : '운동이 완료되었습니다.',
        'finished' : '완료!',
        'loading_sounds' : '음성 데이터 로딩 중...'
    },
    'ja': {
        'all': 'すべて選択',
        'none': 'すべて解除',
        'ready': '準備',
        'done': '完了',
        'cancel': 'キャンセル',
        'selected': '選択済み',
        'gap': '間隔',
        'sec': '秒',
        'voice': '📢 音声',
        'bg': '🎵 背景音',
        'shuffle_and_play': 'シャッフルして開始',
        'play_or_pause': '再生 / 一時停止',
        'resume': '再開',
        'pause': '一時停止',
        'steps': '進行中',
        'status_info': '⚙️をタップして、ルーチンに追加する動作を選択できます。',
        'alert_min_one': '少なくとも1つ以上の動作を選択してください！',
        'status_finished': 'トレーニングが終了しました。',
        'finished': '終了！',
        'loading_sounds' : ''
    },
    'zh': {
        'all': '全选',
        'none': '全取消',
        'ready': '准备',
        'done': '完成',
        'cancel': '取消',
        'selected': '已选择',
        'gap': '间隔',
        'sec': '秒',
        'voice': '📢 语音',
        'bg': '🎵 背景音',
        'shuffle_and_play': '随机打乱并开始',
        'play_or_pause': '播放 / 暂停',
        'resume': '继续',
        'pause': '暂停',
        'steps': '进行中',
        'status_info': '点击 ⚙️ 即可选择要添加到训练计划中的动作。',
        'alert_min_one': '请至少选择一个动作！',
        'status_finished': '训练已完成。',
        'finished': '完成！',
        'loading_sounds' : ''
    },
    'es': {
        'all': 'Seleccionar todo',
        'none': 'Deseleccionar todo',
        'ready': 'Listo',
        'done': 'Hecho',
        'cancel': 'Cancelar',
        'selected': 'Seleccionado',
        'gap': 'Intervalo',
        'sec': 'seg',
        'voice': '📢 Voz',
        'bg': '🎵 Fondo',
        'shuffle_and_play': 'Mezclar y Empezar',
        'play_or_pause': 'Reproducir / Pausa',
        'resume': 'Reanudar',
        'pause': 'Pausa',
        'steps': 'En curso',
        'status_info': 'Toca ⚙️ para seleccionar los movimientos que quieras añadir a tu rutina.',
        'alert_min_one': '¡Selecciona al menos un movimiento!',
        'status_finished': 'Entrenamiento completado.',
        'finished': '¡Terminado!',
        'loading_sounds' : ''
    }
};

// 현재 언어 설정 (지원하지 않는 언어면 'en'으로 설정)
// 'ko-KR', 'en-US', 'ja-JP' 등의 형태로 반환됩니다.
const userLang = (navigator.language || navigator.userLanguage).substring(0, 2); 
// substring(0, 2)를 통해 'ko', 'en', 'ja' 처럼 앞의 두 글자(언어 코드)만 추출합니다.
const currentLang = labels[userLang] ? userLang : 'en';
const i18n = labels[currentLang];